name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - release
      - release/*
      - develop
      - develop/*
      - feature/*
  pull_request:
    branches:
      - main
      - release
      - release/*
      - develop
      - develop/*
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Start
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          TZ: Asia/Tokyo

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Start
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
